WidgetTest/Controllers/HomeController.cs
// ***********************************************************************
// Assembly         : WidgetTest
// Author           : Tim Conrad
// Created          : 11-08-2016
//
// Last Modified By : Tim Conrad
// Last Modified On : 11-08-2016
// ***********************************************************************
// <copyright file="HomeController.cs" company="Conrad Enterprise, Inc.">
//     Copyright Conrad Enterprise, Inc. ©  2016
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Web.Mvc;

namespace WidgetTest.Controllers
{
    /// <summary>
    /// Class HomeController.
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class HomeController : Controller
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Abouts this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult About()
        {
            ViewBag.Message = "Widget Test Case Description";

            return View();
        }

        /// <summary>
        /// Contacts this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Contact()
        {
            ViewBag.Message = "Conrad Enterprise, Inc.";

            return View();
        }
    }
}

WidgetTest/Controllers/WidgetController.cs
// ***********************************************************************
// Assembly         : WidgetTest
// Author           : Tim Conrad
// Created          : 11-08-2016
//
// Last Modified By : Tim Conrad
// Last Modified On : 11-08-2016
// ***********************************************************************
// <copyright file="WidgetController.cs" company="Conrad Enterprise, Inc.">
//     Copyright Conrad Enterprise, Inc. ©  2016
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WidgetTest.Model;
using WidgetTest.Models;
using WidgetTest.Repository;

namespace WidgetTest.Controllers
{
    /// <summary>
    /// Class WidgetController.
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class WidgetController : Controller
    {
        /// <summary>
        /// The widget repository
        /// </summary>
        private readonly IWidgetRepository _widgetRepository;
        /// <summary>
        /// The state repository
        /// </summary>
        private readonly IStateRepository _stateRepository;

        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetController"/> class.
        /// </summary>
        public WidgetController()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetController"/> class.
        /// </summary>
        /// <param name="widgetRepository">The widget repository.</param>
        /// <param name="stateRepository">The state repository.</param>
        public WidgetController(IWidgetRepository widgetRepository, IStateRepository stateRepository)
        {
           
            _widgetRepository = widgetRepository;
            _stateRepository = stateRepository;
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Index()
        {
            var widgets = _widgetRepository.GetAll().OrderBy(w => w.Name);
            var states = _stateRepository.GetAll().OrderBy(s => s.StateName);
            OrderWidgetViewModel model = new OrderWidgetViewModel
            {
                Widgets = widgets,
                States = states
            };

            return View(model);
        }

        /// <summary>
        /// Creates the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns>ActionResult.</returns>
        [HttpPost]
        public ActionResult Order(OrderWidgetViewModel model)
        {
            ReloadModel(model);
            if (ModelState.IsValid)
            {
                CalculateTotal(model);
            }
            return View("Index", model);
        }

        /// <summary>
        /// Reloads the model.
        /// </summary>
        /// <param name="model">The model.</param>
        private void ReloadModel(OrderWidgetViewModel model)
        {
            model.Widgets = _widgetRepository.GetAll();
            model.States = _stateRepository.GetAll();

        }

        /// <summary>
        /// Gets the state tax rate.
        /// </summary>
        /// <param name="states">The states.</param>
        /// <param name="id">The identifier.</param>
        /// <returns>System.Double.</returns>
        private double GetStateTaxRate(IEnumerable<State> states, int id )
        {
            if (states == null) return 0.00;
            var selectedState = states.FirstOrDefault(i => i.StateId == id);
            return selectedState?.TaxRate.TaxBaseRate ?? 0.00;
        }

        /// <summary>
        /// Gets the widget discount.
        /// </summary>
        /// <param name="widgets">The widgets.</param>
        /// <param name="id">The identifier.</param>
        /// <returns>System.Double.</returns>
        private double GetWidgetDiscount(IEnumerable<Widget> widgets, int id)
        {
            if (widgets == null) return 0.00;
            var selectedWidget = widgets.FirstOrDefault(w => w.WidgetId == id && w.DiscountAvailable == true);
            return selectedWidget?.Discount.DiscountPercentage ?? 0.00;
        }

        /// <summary>
        /// Gets the widget base price.
        /// </summary>
        /// <param name="widgets">The widgets.</param>
        /// <param name="id">The identifier.</param>
        /// <returns>System.Double.</returns>
        private double GetWidgetBasePrice(IEnumerable<Widget> widgets, int id)
        {
            if (widgets == null) return 0.00;
            var selectedWidget = widgets.FirstOrDefault(w => w.WidgetId == id);
            return selectedWidget?.BasePrice ?? 0.00;

        }
        /// <summary>
        /// Calculates the total.
        /// </summary>
        /// <param name="model">The model.</param>
        private void CalculateTotal(OrderWidgetViewModel model)
        {
            double taxRate = GetStateTaxRate(model.States, model.StateId);
            double discountRate = GetWidgetDiscount(model.Widgets, model.WidgetId);
            double widgetBasePrice = GetWidgetBasePrice(model.Widgets, model.WidgetId);

            double widgetSubTotal = widgetBasePrice*model.Quantity;
            double discountTotal = widgetSubTotal*(discountRate/100);
            double widgetTotal = widgetSubTotal-discountTotal;
            double salesTax = Math.Abs(taxRate) <= 0 ? 0.00 : (widgetTotal * (taxRate / 100));
            double grandTotal = widgetTotal + salesTax;

            model.TaxRate = taxRate;
            model.DiscountTotal = discountTotal;
            model.WidgetBasePrice = widgetBasePrice;
            model.SalesTax = salesTax;
            model.Total = grandTotal;
            model.Success = true;
        }

        ///// <summary>
        ///// Releases unmanaged resources and optionally releases managed resources.
        ///// </summary>
        ///// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        _widgetRepository.Dispose();
        //        _stateRepository.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

WidgetTest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    Please create an ASP.Net MVC application to showcase your development skills in .Net. The application should let
    the user pick widgets from a given list, enter quantity and state. When the user clicks calculate button, it should
    display discount, sales tax and total price.
</p><br/>
 <p>
    All Widgets should have a name, base price, and discount indicator (true/false).
    Widgets are given a discount of 10% if the discount indicator is true. The total price of a widget should be determined by
    adding the base price - discount (if applicable) + tax. Tax is calculated based on the currently selected state. All states
    have a 5% flat tax rate except for TX and FL (which have no  tax rate of 0%). You can store the data in memory or use
    Microsoft SQL Server Compact 4.0 which can be downloaded from <a href="https://www.microsoft.com/en-us/download/details.aspx?id=17876">here</a>.
    If you don’t have Visual Studio, you can download Community Edition from
    <a href="https://beta.visualstudio.com/vs/community/">here</a>
</p><br />
<p>
    Please showcase your knowledge of dependency injection and layered/hexagonal architecture. You can use any dependency
    injection library you are familiar with. The solution should also have unit tests. You can use MSTest or any xUnit testing
    framework. Provide some examples of mocking in your unit tests. You are free to choose any mocking library.
</p><br />
<p>
    Please email the code to the recruiter or you can save it in your public github and give us read-only access.
</p>
<br/>
<br />
<br />

WidgetTest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<!-- Inner Page Content // Start -->

<div class="inner-page">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <!-- Inner Page Content Sidebar -->
                <div class="page-sidebar">
                    <!-- Page Title -->
                    <div class="page-title br-pink">
                        <!-- Inner Page Title // Heading -->
                        <h2>Contact Us</h2>
                        <!-- Paragraph -->
                        <p>
                            Providing software development and consulting services to small, medium and large businesses. Specializing in Microsoft Technologies.
                        </p>
                    </div>
                    <!-- Sidebar Links -->
                    <div class="sidebar-link col-disable">
                        <!-- Search Box -->
                        <div class="search">
                        </div>
                        <ul class="list-unstyled">
                            <li><a href="@Url.Action("Index","Home")" class="animated">Home <i class="fa fa-angle-double-right"></i></a></li>
                            <li><a href="@Url.Action("About","Home")" class="animated">About Us <i class="fa fa-angle-double-right"></i></a></li>
                            <li><a href="@Url.Action("Index","Widget")" class="animated">Order Widgets <i class="fa fa-angle-double-right"></i></a></li>
                            <li><a href="@Url.Action("Contact","Home")" class="animated">Contact Us <i class="fa fa-angle-double-right"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Main-bar Column -->
            <div class="col-md-9">
                <div class="page-mainbar contactus">
                    <!-- Heading -->
                    <h3>Corporate Office</h3>
                    <!-- Contact Us Content -->
                    <div class="contactus-content">
                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <!-- Contact Us Content Item -->
                                <div class="content-item">
                                    <!-- Icon -->
                                    <i class="fa fa-map-marker lblue"></i>
                                    <!-- Heading -->
                                    <h4>Address</h4>
                                    <!-- Paragraph -->
                                    <p class="grey">8 Chase gayton Drive Suite 325 Henrico, Virginia 23238 - 6511</p>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4">
                                <!-- Contact Us Content Item -->
                                <div class="content-item">
                                    <!-- Icon -->
                                    <i class="fa fa-envelope red"></i>
                                    <!-- Heading -->
                                    <h4>Email</h4>
                                    <!-- Paragraph -->
                                    <p><a href="mailto:tim@conradenterprise.com">tim@conradenterprise.com</a><br /><a href="mailto:tbconrad@gmail.com">tbconrad@gmail.com</a></p>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4">
                                <!-- Contact Us Content Item -->
                                <div class="content-item">
                                    <!-- Icon -->
                                    <i class="fa fa-phone-square green"></i>
                                    <!-- Heading -->
                                    <h4>Voice Call</h4>
                                    <!-- Paragraph -->
                                    <p><a href="#">804 - 405 - 2072</a><br /></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Heading -->
                    <!-- Heading -->
                    <div class="contact-form">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <!-- Google Map -->
                                <iframe scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3160.623019559143!2d-77.59098338426081!3d37.61103037978963!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89b16b193ac194cb%3A0x4f4a0cc5cbbcdb87!2s8+Chase+Gayton+Dr%2C+Henrico%2C+VA+23238!5e0!3m2!1sen!2sus!4v1478766215584"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inner Page Content // End -->

WidgetTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<!-- Inner Page Content // Start -->

<div class="inner-page">
    <div class="container">
        <div class="page-mainbar resume">
            <!-- Resume Header -->
            <div class="resume-header">
                <!-- Image -->
                <img src="~/img/tim.jpg" class="img-responsive" alt="" />
                <!-- Heading -->
                <h2>Tim Conrad</h2>
                <!-- Paragraph -->
                <p class="grey">Professional Software Engineer, Business Owner</p>
            </div>
            <!-- Resume Content -->
            <div class="resume-content">
                <!-- About -->
                <div class="row">
                    @*<div class="col-md-2 col-sm-4">*@
                    <!-- Heading -->
                    @*<h3><i class="fa fa-angle-right"></i> About Me</h3>
                        </div>*@
                    <div class="col-md-12 col-sm-8">
                        <!-- Resume Details -->
                        <div class="resume-details br-red animated">
                            <!-- Heading -->
                            <h4>Acme Widget Co.</h4>
                            <span>International Widget Sales</span>
                            <!-- Paragraph -->
                            <p>The Acme Widget Co. is a ficticious company used in a programming test case to shocase development expertise in a small WebApi and MVC project.</p>
                            <p><br/>
                                Acme Widget Test is a test project for PRA Group of Virginia Beach, VA. This is a coding test to see how the individual
                                coder tackles a coding problem using WebApi, MVC, Razor and Unit Test technologies. This is a simple Widget Ordering system to allow the user to
                                select a widget, their state and the quantity of the widget they want to purchase and then calculate discounts, taxes and totals.
                            </p>
                            <br />
                            <br />
                            <p>
                                @Html.ActionLink("Order Widgets Now!  \u00BB", "Index", "Widget", null, new { @class = "btn btn-primary btn-lg" })
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inner Page Content // End -->